# Generated by Django 4.0.4 on 2022-04-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='titles',
        ),
    ]
